device:
  size: [7000, 2000]
  offset_from_edge: 800

# resonator
resonator:
  type: 0.25
  frequency: 5.5
  frequency_correction: 0.0
  eps: 11
  substrate_h: 1500
  geometry:
    w: 1.8
    g: 1
    coupling_length: 200
    openend_length: 1200
    distance_from_waveguide: 0
    radius: 20
    num: 3

# feedline
feedline:
  w: 1.8
  g: 1
  pad:
    size: 150
    gap: 50